ImageGallery.Client/Models/ErrorViewModel.cs
using System;

namespace ImageGallery.Client.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ImageGallery.Client/ViewModels/AddImageViewModel.cs
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ImageGallery.Client.ViewModels
{
    public class AddImageViewModel
    {
        public List<IFormFile> Files { get; set; } = new List<IFormFile>();

        [Required]
        public string Title { get; set; }
    }
}

ImageGallery.Client/ViewModels/EditImageViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ImageGallery.Client.ViewModels
{
    public class EditImageViewModel
    {
        [Required]
        public string Title { get; set; }

        [Required]
        public Guid Id { get; set; }
    }
}

ImageGallery.Client/ViewModels/ErrorViewModel.cs
namespace ImageGallery.Client.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ImageGallery.Client/ViewModels/GalleryIndexViewModel.cs
using ImageGallery.Model;
using System.Collections.Generic;

namespace ImageGallery.Client.ViewModels
{
    public class GalleryIndexViewModel
    {
        public IEnumerable<Image> Images { get; }

        public GalleryIndexViewModel(IList<Image> images)
        {
            Images = images;
        }
    }
}

ImageGallery.Client/Controllers/GalleryController.cs
using ImageGallery.Client.Models;
using ImageGallery.Client.Services;
using ImageGallery.Client.ViewModels;
using ImageGallery.Model;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace ImageGallery.Client
{
    public class GalleryController : Controller
    {
        private const string ApplicationJsonMediaType = "application/json";
        private readonly IImageGalleryHttpClient imageGalleryHttpClient;

        public GalleryController(IImageGalleryHttpClient imageGalleryHttpClient)
        {
            this.imageGalleryHttpClient = imageGalleryHttpClient;
        }

        public async Task<IActionResult> Index()
        {
            // call the API
            var httpClient = imageGalleryHttpClient.GetClient();

            var response = await httpClient.GetAsync("api/images");

            if (response.IsSuccessStatusCode)
            {
                var imagesAsString = await response.Content.ReadAsStringAsync();
                var images = JsonConvert.DeserializeObject<IList<Image>>(imagesAsString);
                var galleryIndexViewModel = new GalleryIndexViewModel(images);
                return View(galleryIndexViewModel);
            }

            throw new Exception($"A problem happend while calling the API: {response.ReasonPhrase}");
        }

        public async Task<IActionResult> EditImage(Guid id)
        {
            // call the API
            var httpClient = imageGalleryHttpClient.GetClient();
            var response = await httpClient.GetAsync($"api/images/{id}");
            if (response.IsSuccessStatusCode)
            {
                var imageAsString = await response.Content.ReadAsStringAsync();
                var image = JsonConvert.DeserializeObject<Image>(imageAsString);
                var editImageViewModel = new EditImageViewModel
                {
                    Id = image.Id,
                    Title = image.Title,
                };
                return View(editImageViewModel);
            }
            throw new Exception($"A problem happend while calling the API: {response.ReasonPhrase}");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditImage(EditImageViewModel editImageViewModel)
        {
            if (ModelState.IsValid == false)
            {
                return View();
            }

            // create an ImageForUpdate instatnce
            var imageForUpdate = new ImageForUpdate
            {
                Title = editImageViewModel.Title,
            };
            var serializedImageForUpdate = JsonConvert.SerializeObject(imageForUpdate);

            // call the API
            var httpClient = imageGalleryHttpClient.GetClient();
            var requestUri = $"api/images/{editImageViewModel.Id}";
            var content = new StringContent(serializedImageForUpdate, Encoding.Unicode, ApplicationJsonMediaType);
            var response = await httpClient.PutAsync(requestUri, content);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            throw new Exception($"A problem happend while calling the API: {response.ReasonPhrase}");
        }

        public async Task<IActionResult> DeleteImage(Guid id)
        {
            // call the API
            var httpClient = imageGalleryHttpClient.GetClient();
            var response = await httpClient.DeleteAsync($"api/images/{id}");

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            throw new Exception($"A problem happend while calling the API: {response.ReasonPhrase}");
        }

        public IActionResult AddImage()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddImage(AddImageViewModel addImageViewModel)
        {
            if (ModelState.IsValid == false)
            {
                return View();
            }

            // create an ImageForCreation instance
            var imageForCreation = new ImageForCreation
            {
                Title = addImageViewModel.Title,
            };

            // take the first (only) file in the Files list
            var imageFile = addImageViewModel.Files.First();
            if (imageFile.Length > 0)
            {
                using (var fileStrem = imageFile.OpenReadStream())
                using (var ms = new MemoryStream())
                {
                    await fileStrem.CopyToAsync(ms);
                    imageForCreation.Bytes = ms.ToArray();
                }
            }

            // serialize it
            var serializedImageForCreation = JsonConvert.SerializeObject(imageForCreation);

            // call the API
            var httpClient = imageGalleryHttpClient.GetClient();
            var content = new StringContent(serializedImageForCreation, Encoding.Unicode, ApplicationJsonMediaType);
            var response = await httpClient.PostAsync("api/images", content);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            throw new Exception($"A problem happend while calling the API: {response.ReasonPhrase}");
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ImageGallery.Client/Views/Gallery/AddImage.cshtml
@model ImageGallery.Client.ViewModels.AddImageViewModel

<div class="container mt-4">

    <h2>AddImage</h2>

    <form asp-action="AddImage" method="post" role="form" enctype="multipart/form-data">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="Title">Your image's title</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Files">The image file</label>
            <input asp-for="Files" type="file" class="form-control" accept=".jpg,.jpeg" />
        </div>

        <div class="form-group">
            <input type="submit" value="Add image" class="btn btn-primary" />
        </div>
    </form>

    <div>
        <a asp-action="Index">Back to Home</a>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/site.addImage.js"></script>
}

ImageGallery.Client/Views/Gallery/EditImage.cshtml
@model ImageGallery.Client.ViewModels.EditImageViewModel

<div class="container mt-4">

    <h2>Edit Image Title</h2>

    <form asp-action="EditImage" method="post" role="form">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="Title">Your image's title</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input type="submit" value="Change title" class="btn btn-primary" />
        </div>

    </form>

    <div>
        <a asp-action="Index">Back to Home</a>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ImageGallery.Client/Views/Gallery/Index.cshtml
@model ImageGallery.Client.ViewModels.GalleryIndexViewModel
<div class="container mt-4">
    <div class="row">
        @foreach (var item in Model.Images)
        {
            <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3">
                <div>
                    <img class="img-thumbnail" src="@("http://localhost:58828/images/" + item.FileName)" />
                </div>
                <div>
                    <div class="h5">@item.Title</div>
                    <div class="mb-4">
                        <a asp-action="EditImage" asp-controller="Gallery" asp-route-id="@item.Id">Edit title</a> |
                        <a asp-action="DeleteImage" asp-controller="Gallery" asp-route-id="@item.Id">Delete image</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    <script src="~/js/site.index.js"></script>
}

ImageGallery.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Image Gallery</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/css/bootstrap.min.css"
              asp-fallback-href="~/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>


    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
        <a asp-area="" asp-controller="Gallery" asp-action="Index" class="navbar-brand">Image Gallery</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a asp-area="" asp-controller="Gallery" asp-action="Index" class="nav-link">
                        Home <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="" asp-controller="Gallery" asp-action="AddImage" class="nav-link">
                        Add an image
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Image Gallery</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/js/jquery.js"></script>
        <script src="~/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/js/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/bootstrap.min.js"
                asp-fallback-src="~/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>